export const VOITEST_API_URL = "https://arc72-idx.nautilus.sh"; // TESTNET
export const VOIMAIN_API_URL = "https://mainnet-idx.nautilus.sh"; // MAINNET

export const AIRDROP_FUNDER =
  "62TIVJSZOS4DRSSYYDDZELQAGFYQC5JWKCHRBPPYKTZN2OOOXTGLB5ZJ4E";
export const AIRDROP_CTC_INFO = 5211;

export const STAKING_FUNDER = "62TIVJSZOS4DRSSYYDDZELQAGFYQC5JWKCHRBPPYKTZN2OOOXTGLB5ZJ4E";
export const STAKING_CTC_INFO = 400350;

export const SECOND_IN_MONTH = 2630000;
